# chatbot/config.yaml
openai:
  api_key: "your_api_key"
  api_base: "https://gms.ssafy.io/gmsapi/api.openai.com/v1/responses"

anthropic:
  api_key: "your_api_key"

google:
  credentials: "/path/to/your/service-account.json"

model:
  name: "gpt-4.1"
  temperature: 0.0

manual_path: "manuals/siseon_manual.pdf"
