ydlidar_ros2_driver_node:
  ros__parameters:
    port: /dev/ttyUSB0
    frame_id: laser_frame
    ignore_array: ""
    baudrate: 921600
    lidar_type: 3
    device_type: 0
    isSingleChannel: false
    intensity: true
    intensity_bit: 8
    sample_rate: 30.0
    frequency: 30.0
    m1_mode: 0
    m2_mode: 0
    m3_mode: 0
    abnormal_check_count: 4
    fixed_resolution: false
    reversion: false
    inverted: false
    auto_reconnect: true
    support_motor_dtr: false
    angle_max: 180.0
    angle_min: -180.0
    range_max: 1.0
    range_min: 0.025
    invalid_range_is_inf: false
    debug: false

